trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'drop'

jobs:
  - job: Build
    displayName: 'Build and publish WAR'
    steps:
      - task: Gradle@3
        inputs:
          workingDirectory: 'spring-mvc-fiap'
          gradleWrapperFile: 'spring-mvc-fiap/gradlew'
          tasks: 'clean build'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'

      - task: CopyFiles@2
        inputs:
          contents: '**/build/libs/ROOT.war'
          targetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: '$(artifactName)'

  - job: Deploy
    displayName: 'Deploy to Azure App Service'
    dependsOn: Build
    steps:
      # 1) Baixa os artefatos publicados no job Build
      - download: current

      # 2) Lista tudo dentro de Pipeline.Workspace para confirmar a estrutura
      - script: |
          echo "Listando Workspace inteiro:"
          ls -R $(Pipeline.Workspace)
        displayName: 'Debug – listar diretórios'

      # 3) Deploy apontando para o .war que está dentro de drop
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'AzureConnection'
          appType: 'webAppLinux'
          appName: 'nome-do-seu-app'
          package: '$(Pipeline.Workspace)/drop/*.war'
