trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Service Connection do Azure DevOps (criada em Project Settings → Service connections)
  azureSubscription: 'AzureConnection'

  # Grupo de recursos e nome do App Service
  azureResourceGroup: 'rg-gs-demo'
  azureWebAppName: 'gs-app'

  # Variáveis do Azure SQL
  azureSqlServer: 'server-sqldb-gs-demo'    # sem “.database.windows.net”
  azureSqlDatabase: 'sqldb-gs-demo'
  sqlUser: 'adm@servidor-sqldb-gs-demo'
  sqlPassword: '@Gs12345'

  # Monta a JDBC URL completa para SQL Azure
  CONNECTION_STRING: >-
    jdbc:sqlserver://$(azureSqlServer).database.windows.net:1433;
    database=$(azureSqlDatabase);
    user=$(sqlUser);
    password=$(sqlPassword);
    encrypt=true;
    trustServerCertificate=false;
    hostNameInCertificate=*.database.windows.net;
    loginTimeout=30;

jobs:
  - job: BuildAndDeploy
    displayName: 'Build com Maven e Deploy no App Service'
    steps:
      # 1) Compilar o projeto Spring Boot (pom.xml em s/demo)
      - task: Maven@3
        displayName: 'Compilar com Maven (demo/pom.xml)'
        inputs:
          mavenPomFile: 'demo/pom.xml'
          goals: 'clean package'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'

      # 2) DEBUG: listar demo/target para confirmar o JAR
      - script: |
          echo "=== Conteúdo de $(Build.SourcesDirectory)/demo/target ==="
          ls -l $(Build.SourcesDirectory)/demo/target || echo "(vazio)"
        displayName: 'DEBUG: Listar demo/target'

      # 3) Deploy direto do JAR em demo/target/*.jar para o App Service
      - task: AzureWebApp@1
        displayName: 'Deploy do JAR no App Service'
        inputs:
          azureSubscription: '$(azureSubscription)'
          appName: '$(azureWebAppName)'
          resourceGroupName: '$(azureResourceGroup)'
          # aponta diretamente para o .jar gerado por Maven
          package: 'demo/target/*.jar'
          appSettings: |
            -WEBSITE_RUN_FROM_PACKAGE 1
          configurationStrings: |
            Demosqldb:$(CONNECTION_STRING)
