trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AzureConnection'        # Nome da Service Connection no Azure DevOps
  azureResourceGroup: 'rg-gs-demo'           # Seu resource group
  azureWebAppName: 'gs-app'                   # Nome exato do App Service
  azureSqlServer: 'servidor-sqldb-gs-demo'     # Nome do servidor SQL sem ".database.windows.net"
  azureSqlDatabase: 'sqldb-gs-demo'            # Nome do banco de dados
  sqlUser: 'adm@servidor-sqldb-gs-demo'        # Usuário completo (já com @servidor)
  sqlPassword: '@Gs12345'                      # Senha do SQL
  CONNECTION_STRING: >-
    jdbc:sqlserver://$(azureSqlServer).database.windows.net:1433;
    database=$(azureSqlDatabase);
    user=$(sqlUser);
    password=$(sqlPassword);
    encrypt=true;
    trustServerCertificate=false;
    hostNameInCertificate=*.database.windows.net;
    loginTimeout=30;

  artifactName: 'drop'

jobs:
  - job: Build
    displayName: 'Build e publicar JAR'
    steps:
      - task: Maven@3
        displayName: 'mvn clean package'
        inputs:
          mavenPomFile: 'demo/pom.xml'
          goals: 'clean package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'

      - task: CopyFiles@2
        displayName: 'Copiar JAR para ArtifactStagingDirectory'
        inputs:
          contents: 'demo/target/*.jar'
          targetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publicar artifact'
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: '$(artifactName)'

  - job: Deploy
    displayName: 'Deploy no App Service'
    dependsOn: Build
    steps:
      - download: current
      - script: ls -R $(Pipeline.Workspace)

      - task: AzureWebApp@1
        displayName: 'Deploy e configurar Connection String'
        inputs:
          azureSubscription: '$(azureSubscription)'
          appName: '$(azureWebAppName)'
          resourceGroupName: '$(azureResourceGroup)'
          package: '$(Pipeline.Workspace)/drop/*.jar'
          appSettings: |
            -WEBSITE_RUN_FROM_PACKAGE 1
          configurationStrings: |
            Demosqldb:$(CONNECTION_STRING)
